name: ncr_bsp_hmac_dart
description: Dart HTTP client for NCR BSP HMAC
version: 0.1.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  http:
  crypto:
  intl:
  args:
  uuid:

dev_dependencies:
  lints: ^1.0.0
