name: Go Tests
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test GET
      run: cd go/examples/get && go test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SHARED_KEY: ${{ secrets.SHARED_KEY }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        GITHUB_ACTION: true
    - name: Test POST
      run: cd go/examples/post && go test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SHARED_KEY: ${{ secrets.SHARED_KEY }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        GITHUB_ACTION: true
