name: JS Tests 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Test with jest
      run: npm test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SHARED_KEY: ${{ secrets.SHARED_KEY }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
